background_opacity: 0.95

window:
  dimensions:
    columns: 120
    lines: 30

  padding:
    x: 5
    y: 5

font:
  size: 12.0

  normal:
    family: JetBrains Mono
    style: Regular

  bold:
    family: JetBrains Mono
    style: Bold

  italic:
    family: JetBrains Mono
    style: Italic

  offset:
    x: 0
    y: 1

# Colors (Doom One)
colors:
  primary:
    background: '0x282c34'
    foreground: '0xbbc2cf'

  normal:
    black:   '0x282c34'
    red:     '0xff6c6b'
    green:   '0x98be65'
    yellow:  '0xecbe7b'
    blue:    '0x51afef'
    magenta: '0xc678dd'
    cyan:    '0x46d9ff'
    white:   '0xbbc2cf'
