brew "asdf"
brew "diff-so-fancy"
brew "direnv"
brew "docker"
brew "fish"
brew "fzf"
brew "ghq"
brew "git"
brew "git-chglog/git-chglog/git-chglog"
brew "git-now"
brew "gnupg"
brew "mas"
brew "jq"
brew "nkf"
brew "pinentry-mac"
brew "tmux"
brew "tree"

cask "bitwarden"
cask "google-chrome"
cask "slack"
cask "visual-studio-code"
cask "notion"
cask "iterm2"
cask "boostnote"
cask "jetbrains-toolbox"
cask "cmd-eikana"
cask "gifox"
cask "google-drive"
cask "dropbox"
cask "imageoptim"
cask "appdelete"
cask "obsidian"
cask "spotify"
cask "zoom"
cask "microsoft-teams"

tap "homebrew/cask-fonts"
cask "font-jetbrains-mono"

mas "Amphetamine", id: 937984704
