style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
  comment:
    color: blue
  snippet:
    color: white

finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

cheats:
  paths:
    - ~/.config/navi/cheats

shell:
  command: bash
