matches:
  # Python
  - trigger: ";pdb"
    replace: "import ipdb\n\nipdb.set_trace()"
  
  - trigger: ";t"
    replace: "APP_ENV=test python manage.py test --keepdb $|$"

  - trigger: ";s"
    replace: "print('=' * 30)"

  # Javascript
  - trigger: ";c"
    replace: "console.debug($|$)"

  - trigger: ";deps"
    replace: "// eslint-disable-next-line react-hooks/exhaustive-deps"
